### ISSUE TITLE
"cannot open file 'detours.h'" when building the solution.

### ISSUE THREAD

**Issue by cammysorammy** [per0x1dee/QoS-element#1]
Hi, I used the premake.bat provided in the files, but as i went to compile the project, I was hit with an error about "detours.h." I checked the files, and there is a path for detours, but it just says its not present.

![image](https://github.com/per0x1dee/QoS-element/assets/64805150/b1d34149-bdf8-442a-a8fb-c55ffc209bcc)

here is the error visual studio gives me.

**Comment by per0x1dee** [comment]
Right Click the project in solution explorer, Manage NuGet packages, and
install Microsoft Detours.

**Comment by cammysorammy** [comment]
worked, thanks!

figured i'd let you know that the build output path is to an E:\ drive, which may cause problems with some people.

**Comment by per0x1dee** [comment]
Yes. This is due to me compiling directly to game folder.
If you’re messing with such a WIP project you likely know how to change it
yourself.

**Comment by cammysorammy** [comment]
that makes sense, thanks for helping clear it up! me and a group of people have developed an interest in this, and we have a lot of faith in this project, hope to see more in the future!
