### ISSUE TITLE
[Request] FOV change implementation? (allow for cg_fov?)

### ISSUE THREAD

**Issue by cammysorammy** [per0x1dee/QoS-element#2]
Hey, I was wondering if the idea of allowing for an FOV change was planned for your project? I know one for the Viewmodel FOV is, but I was curious about one in general. One for SP was made, but me and a couple of people are eager to know if one for the MP is possible.

**Comment by per0x1dee** [comment]
If you’re asking for a FOV slider for MP, i can look into it, but this
project is rather dead.

(You can also set it via the external console)

**Comment by cammysorammy** [comment]
That would be super appreciated!

I tried setting it with cg_fov in the MP using the Console GUI to no avail, is there a specific command I should use?

**Comment by per0x1dee** [comment]
You probably have to set sv_cheats first or devmap the map.
Try cg_fovScale as a workaround, otherwise you can share me your discord
username and you could test some stuff prior to it being pushed as i dont
have the time to test myself but this should be rather easy to mess with.

**Comment by cammysorammy** [comment]
sounds good! my discord is `cammy8580` (new username system)
